services:
  backend:
    build: .
    network_mode: "host" # ✅ Use the host network
    environment:
      - MONGO_URI=mongodb://localhost:27017/conversationsDB # 🔹 Use localhost since it's on the host network

  mongo:
    image: mongo:5.0
    network_mode: "host" # ✅ MongoDB also needs to use host network
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
