services:
  backend:
    build: .
    ports:
      - "5000:5000"  # Exposes the port to the host machine
    environment:
      - MONGO_URI=mongodb://mongo:27017/chatdb
    networks:
      - app_network

  mongo:
    image: mongo:5.0
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
    driver: bridge

